server:
  port: 8989
  servlet:
    context-path: /springboot_day3

# 整合Mybatis的相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # driver-class-name: com.mysql.jdbc.Driver
    #新版的需要另一种写法
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootssm?characterEncoding=UTF-8
    uaername: root
    password: root

mybatis:
  mapper-locations: classpath:com/henryshe/mapper/*.xml # 指定mapper配置文件位置
  type-aliases-package: com.henryshe.entity # 指定实体类包名

