server:
  port: 8989
  servlet:
    context-path: /springboot_day3

# 整合Mybatis的相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # driver-class-name: com.mysql.jdbc.Driver
    #新版的需要另一种写法
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.17.157.87:6869/bootssm?useUnicode=true&characterEncoding=utf-8useSSL=true&serverTimezone=GMT%2B8
    uaername: root
    password: 9Kow4Rt

mybatis:
  mapper-locations: classpath:com/henryshe/mapper/*.xml # 指定mapper配置文件位置
  type-aliases-package: com.henryshe.entity # 指定实体类包名